### ISSUE TITLE
Test results are only reported/logged at the end, not continuously

### ISSUE THREAD

**Issue by MikkCZ** [artemrudenko/playwright-teamcity-reporter#1]
All logs are being emitted from `onEnd`, so only after all tests are finished. However [customer reporter interface](https://playwright.dev/docs/test-reporters#custom-reporters) also provides `onTestBegin` and `onTestEnd` function, which allows to report the test independently. The effect of using those instead would be the possibility to see if there are test failures during the build run in TeamCity UI. And also from the times of the logs, it's possible to see roughly how lmuch time the tests took.

**Comment by artemrudenko** [comment]
> I can see from TC documentation why you might have implemented it all via `onEnd`, because you needed to use the suites messages? https://www.jetbrains.com/help/teamcity/service-messages.html#Supported+Test+ServiceMessages

Hi @MikkCZ, if I am not wrong you are right here. Unfortunately there is no any other way to define when suite(sub suite) -started.

**Comment by MikkCZ** [comment]
In the specific setup I am working with now, where we have no parallelisation (a single worker), it seems to work by storing the suite into the reporter's instance variable. According the Playwright documentation, at that situation the files are run sequentially. Their order, and the order of the tests inside, is not guaranteed, but that it's sufficient that only one can run at a time.

Do you think it would be worth creating a PR to support continuous logging for such specific case?

**Comment by artemrudenko** [comment]
> In the specific setup I am working with now, where we have no parallelisation (a single worker), it seems to work by storing the suite into the reporter's instance variable. According the Playwright documentation, at that situation the files are run sequentially. Their order, and the order of the tests inside, is not guaranteed, but that it's sufficient that only one can run at a time.
> 
> Do you think it would be worth creating a PR to support continuous logging for such specific case?

Hi @MikkCZ if this is has value for you than sure. We just need a way to configure this?
Best Regards,
Artem
