### ISSUE TITLE
Test grouping does now work

### ISSUE THREAD

**Issue by rolandz83** [artemrudenko/playwright-teamcity-reporter#3]
Hello, 
The test results are not being grouped by the suite names.
testSuiteStarted and testSuiteFinished are not being picked up by the TC,
so all our tests fall under <no suite> / <no package>  / <no class> when viewed in TC

Only on one test we noticed having a suite name which had a ":" colon character in its test name, text to the left of the colon became the suite name and text to the right of the colon became the test name.
maybe TC is attempting to parse the test name ?

I was expecting test.describe block being the suite name, and not sure how class / package can be assigned for grouping.

Thank you for your help

**Comment by artemrudenko** [comment]
Hi @rolandz83, thank you, will take a look into this. By the way, do you have any repo to reproduce this?

**Comment by rolandz83** [comment]
don't have a repo at the moment but, I did write up a demo test as such:

> test.describe('@demo Demo file2', () => {
>   test("Test#1 ", async({page}) => {
>     await page.goto('https://www.google.com/');
>     await expect(page).toHaveURL('https://www.google.com/');
>   });
> 
>   test("Test#2 ", async({page}) => {
>     await page.goto('https://www.java.com/');
>     await expect(page).toHaveURL('https://ThisIsaFailTest.com/');
>   });
> 
>   test("Test#3 ", async({page}) => {
>     await page.goto('https://playwright.dev/');
>     await expect(page).toHaveURL('https://playwright.dev/');
>   });
> 
>   test("Test#4 ", async({page}) => {
>     expect(true).toBeTruthy();
>   });
> })

Producing the following result. clearly suitestart and finish are there but TC dont seem to be doing anything with them.

![TCreporter](https://user-images.githubusercontent.com/78881730/166525076-6e9573b8-e010-478f-8a31-db15ddc0e309.jpg)
;

and based on what I wrote previously and what I read on TeamCity documentation here https://www.jetbrains.com/help/teamcity/service-messages.html#Interpreting+Test+Names

colon character in the test title does give the test suite name without the use of suitestart/finish but sub categories pacakge and class name does not show up.  I renamed some of my tests as recommended on teamcity. 
**suite name: package/namespace name . class name . test method**

But my confusion comes due to TeamCity documentation, at first I was under the impression that suitestart and finish are the way we group the test, now I read about how TC interpreting the test names seems to me TC is parsing the names for grouping  them, I'm not sure.

**Comment by artemrudenko** [comment]
Hi @rolandz83 , i have added your suite and executed it, and as i can sett the results looks ok:
![image](https://user-images.githubusercontent.com/4124441/166886626-b21a47a1-01b4-44bd-8967-7da0a5805e2a.png)

**Comment by rolandz83** [comment]
Hi @artemrudenko, sorry for the late reply,  my issue was the grouping of the tests inside TeamCity, under Tests tab I should be able to group the tests by suites / packages and classes.  my understanding was testSuiteStarted and testSuiteFinished should be able to help with that but it did not work for me.

**Comment by artemrudenko** [comment]
> Hi @artemrudenko, sorry for the late reply, my issue was the grouping of the tests inside TeamCity, under Tests tab I should be able to group the tests by suites / packages and classes. my understanding was testSuiteStarted and testSuiteFinished should be able to help with that but it did not work for me.

Hi @rolandz83 could you please try with the latest version? when i tried it i was able to apply diff groupings for your example.
Best Regards,
Artem
